rust-lang/gll

- src/generate/rust.rs
- src/runtime.rs
Internal iteration (`for_each`) turned out to take ages optimizing, and generators are unstable, so I went back to iterator adapters, but with less closures, to work around rust-lang/rust#54175.
> Go back to external iteration (for `all`) without generators.

- src/runtime.rs
I've also used this trick in #82, I think it's pretty neat (but I wish we didn't need it!)
> runtime: use renaming to better contain the `traverse` macro.

- macros/tests/basic.rs
- macros/tests/json.rs
> tests: ignore trailing commas in {:#?} output.

- LICENSE-APACHE
- LICENSE-MIT
This removes an unnecessary `Copyright ...` header from `LICENSE-MIT`.
Also, what should we do about the `authors` field in `Cargo.toml`?
> Copy license files from Rust.

- README.md
- macros/tests/basic.rs
- macros/tests/json.rs
- src/generate/rust.rs
- src/generate/templates/header.rs
- src/high.rs
- src/indexing_str.rs
- src/lib.rs
- src/parse_grammar.rs
- src/runtime.rs
This is accomplished by adding an abstraction tool of the form `exists 'a.Foo<'a>`, where the `'a` is used for the [`indexing`](https://docs.rs/indexing) generative lifetime.
> Produce an owned result from parsing.

- src/generate/rust.rs
- src/generate/src.rs
- src/indexing_str.rs
- src/runtime.rs
Builds on https://github.com/rust-lang/gll/pull/98.
> Clippy fixes and others

- macros/src/lib.rs
- macros/tests/basic.rs
- macros/tests/json.rs
- src/generate/rust.rs
- src/generate/src.rs
- src/generate/templates/header.rs
- src/grammar.rs
- src/lib.rs
- src/parse_grammar.rs
- src/runtime.rs
Builds on https://github.com/rust-lang/gll/pull/99
> Apply `#![deny(rust_2018_idioms]` to all crate roots

- src/generate/src.rs
Let's not make it easy to produce undebuggable output.
> generate: make `Src::to_ugly_string` private, to discourage usage.

- src/generate/rust.rs
- src/runtime.rs
Most of this is pretty straight-forward, although I went a bit far on the last commit.
I wish I could get farther, but all of these relative ranges are making it hard to reason about what's possible (I should've known the premature optimizations would eventually come back to haunt me...)
> Don't use "state" for `Rule::Or` parse nodes, and store them separately in the ParseForest.

- Cargo.toml
- macros/tests/basic.rs
- src/generate/rust.rs
- src/parse_grammar.rs
```
A* %% B => (A+ %% B)?
A+ %% B =>  A+ % B B?
```
This means that %% is a separated list with optional trailing separator, but no lone separator.
> Parse %% repetition

- Cargo.toml
- build.rs
- macros/src/lib.rs
- src/generate/rust.rs
- src/lib.rs
- src/parse_grammar.rs
- src/proc_macro.rs
- src/proc_macro_runtime.rs
- src/runtime.rs
- src/scannerless.rs
Fixes #110 and closes #14 (without providing a replacement).
> Parse grammars with `proc_macro` tokens and remove "negative lookahead".

- macros/tests/basic.rs
- src/generate/rust.rs
- src/generate/templates/imports.rs
- src/runtime.rs
*Based on #113, do not merge yet.*
Instead of the generated code poking at `runtime`'s data structures, it now relies on methods of `Parser`, which should be less easy to misuse.
This also removed `fn_input`, which was hackily used as a microoptimization, and broke after #107.
> Introduce a less fragile Parser API.

- src/forest.rs
- src/generate/rust.rs
- src/generate/templates/header.rs
- src/generate/templates/imports.rs
- src/parser.rs
- src/runtime.rs
While not needed right now (the "grammar reflector" in the generated code is just an unit struct), it would be useful for a more dynamic implementation (i.e. an interpreter), which might want/need to have its `ParseNodeKind` be an (interned) index into a context.
> forest: query properties of `ParseNodeKind`s via a "grammar reflector".

- macros/tests/basic.rs
- src/parser.rs
- src/runtime.rs
@CAD97 reduced this in the `wg-grammar` repo, and it turns out the test I added in #114 was already exhibiting the issue!
The problem was that in `A B`, while parsing `B` we kept increasing the `result` range, so it contained `A` too, and when `B` was e.g. `C | D`, you'd end up with `C` (or `D`) nodes with the `A C` (or `A D`) range, which is the wrong one (and caused panics when using the `one_*` APIs).
I fixed it by resetting the `result` range to an empty range at the end of `A` / start of `B`, when saving `A` for later, and combining the range for `A` with the one for `B` when adding the parse node for `A B`.
> runtime: reset the result to the start of `B` in `A B`.

- Cargo.toml
- build.rs
- macros/src/lib.rs
- src/generate/rust.rs
- src/parse_grammar.rs
- src/proc_macro.rs
- src/scannerless.rs
See https://github.com/lykenware/grammer/pull/4.
> Update for `grammer` using interning.

- Cargo.toml
- macros/tests/basic.rs
- macros/tests/json.rs
- src/generate/rust.rs
- src/parse_grammar.rs
- src/runtime.rs
Now they should look identical to syntax that can be used to create them.
*Blocked on https://github.com/LykenSol/grammer/pull/7 and https://github.com/rust-lang/gll/pull/123.*
> Improve printing of expected patterns in parse errors.

- Cargo.toml
- build.rs
- macros/src/lib.rs
- src/generate/rust.rs
- src/generate/templates/header.rs
- src/generate/templates/imports.rs
- src/parse_grammar.rs
- src/runtime.rs
See https://github.com/LykenSol/grammer/pull/9.
> Update for grammer not requiring &mut Context for interning.

- Cargo.toml
- macros/tests/basic.rs
- macros/tests/json.rs
- src/runtime.rs
See https://github.com/LykenSol/grammer/pull/12.
> Update grammer for ParseError-related fixes.

- Cargo.toml
- src/generate/rust.rs
- src/generate/templates/header.rs
- src/runtime.rs
See https://github.com/LykenSol/grammer/pull/14.
> Update grammer for Node<'i, P> -> Node<'i, G>.

- macros/src/lib.rs
- src/generate/rust.rs
This is needed to use latest `gll` (which is more forgiving field-wise) with `wg-grammar`.
> Fixes for new errors from lints (rust_2018_idioms, ambiguous_associated_items).
